---
exclude: ['README.markdown']
pygments: true
safe: false

name: Octokan
description: 'A Better Issue Queue for GitHub'

author: Wiredcraft
email: info@wiredcraft.com
url: http://wiredcraft.com/down

ga: "UA-48007565-1"
gauges: "52fb27825dd0531cc6001f16"
