---
exclude: ['README.markdown']
pygments: true
safe: false

name: Octokan
description: 'A Better Issue Queue for GitHub'

author: Wiredcraft
email: info@wiredcraft.com
url: http://wiredcraft.com/down

# ga: XXX
# gauges: XXX
